### ISSUE TITLE
problem with Cyrillic Forums

### ISSUE THREAD

**Issue by inrussiawithhate** [HackThis/hackthis.co.uk#180]
Hi ... when I post topic content written in Cyrillic or published, but when I click it me back in the index or simply returns an error that the post is too short. Is this bug and how to fix it?

**Comment by 0x6C77** [comment]
> As the HackThis!! community’s first language is English, I will always post contributions in English to enable all to understand

https://www.hackthis.co.uk/conduct

**Comment by inrussiawithhate** [comment]
na maika ti v ustata gei
