### ISSUE TITLE
CSS / JS / images not found through KeyCDN

### ISSUE THREAD

**Issue by biinari** [HackThis/hackthis.co.uk#210]
I am getting a 404 Not Found error on all stylesheets, javascripts and images through KeyCDN, e.g. `https://hackthis-10af.kxcdn.com/files/css/min/dark/main.css?1446678416`

Changing URLs to load straight from www.hackthis.co.uk works fine, e.g. `https://www.hackthis.co.uk/files/css/min/dark/main.css?1446678416`

**Comment by 0x6C77** [comment]
Thanks for the heads up - this issue has now been resolved

**Comment by biinari** [comment]
Ace, thanks @0x6C77
